import { Inter } from "next/font/google";
import "./globals.css";
import axios from "axios";
import Providers from "./providers";
import Navbar from "./components/navbar";

axios.defaults.withCredentials = true

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RAVCOMP STORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
         
        {children}
        </Providers>
        </body>
    </html>
  );
}
